[build]
builder = "NIXPACKS"
buildCommand = "cd server && chmod +x ../gradlew && ../gradlew :server:clean :server:build -x check -x test"

[deploy]
startCommand = "java -jar server/build/libs/server-all.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
